apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: iedesnoek/webevents:v5
          env:
            - name: "host"
              value: "postgres.default"
            - name: "user"
              value: "postgres"
            - name: "password"
              value: "Piloten2030"
            - name: "dbname"
              value: "webevents"
            - name: "port"
              value: "5432"


