apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  POSTGRES_DB: "webevents"
  POSTGRES_USER: "testUser"
  POSTGRES_PASSWORD: "testPassword"
  HOST: "postgresdb.default"
  PORT: "5432"